version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "02:00"
      timezone: "Asia/Tokyo"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "dependency"
    commit-message:
      prefix: "dependabot"
      include: "scope"
    open-pull-requests-limit: 10
