name: control milestone

on:
  milestone:
    types:
      - "created"
      - "edited"
      - "opened"
      - "closed"

jobs:
  validate-title:
    runs-on: ubuntu-latest
    if: github.event.action == 'created' || github.event.action == 'edited' || github.event.action == 'opened'
    steps:
      - uses: actions/checkout@v3
      - name: check title
        run: |-
          ./.github/semver.py "${{ github.event.milestone.title }}" v

  create-tag:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: clone repository
        run: |
          url=$(echo ${{ github.repositoryUrl }} | sed -e 's%git://%https://x-access-token:${{ steps.generate_token.outputs.token }}@%')
          git clone --depth 1 --branch ${{ github.ref_name }} $url .
      - name: get app version
        id: app_version
        run: |
          ./.github/semver.py "${{ github.event.milestone.title }}" v
      - name: create git tag
        run: |
          tag=v${{ steps.app_version.outputs.version }}
          git tag $tag
          git push origin $tag
